# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zihan Zhou
email: footoredo@gmail.com
safe_email: footoredo [at] gmail [dot] com
description: >- # this means to ignore newlines until "baseurl:"
  I start studying at the University of Toronto! I am supervised by <a href="https://animesh.garg.tech/">Prof. Animesh Garg</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zihan.page" # the base hostname & protocol for your site, e.g. http://example.com
logo: https://i.ibb.co/ynkCkj8/oooo-plus-70.png
# ico_favicon: /favicon.ico
# png_favicon: /favicon.png
twitter_username: footoredo
github_username: footoredo

links:
  - name: Google Scholar
    url: https://scholar.google.com/citations?user=HwFGzZMAAAAJ
  - name: Curriculum Vitae
    url: /curriculum-vitae
  - name: Github
    url: https://github.com/footoredo
  - name: GPG public key
    url: https://raw.githubusercontent.com/footoredo/files/main/main.gpg

# Build settings
# theme: minimal
remote_theme: footoredo/minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

repository: footoredo/academic

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
